# Generated by Django 4.2.7 on 2023-11-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50000)),
                ('address', models.TextField(max_length=50000)),
                ('birthday', models.DateField()),
            ],
        ),
    ]
